@rem ====================================================================================
@rem Generated by IntelliFactory.Build.Automation
@rem ====================================================================================
@echo off
setlocal
set PATH=%PATH%;%ProgramFiles(x86)%\MSBuild\12.0\Bin
set PATH=%PATH%;tools\NuGet
del /Q %~dp0packages
NuGet.exe restore
MSBuild.exe /p:Configuration=Release /verbosity:minimal
